services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/GoldWindowsXPSP32016DriversV2.0ByComputerWormsTeam/Gold%20Windows%20XP%20SP3%202016%20%2B%20Drivers%20v2.0%20By%20Computer%20Worms%20Team.rar/Gold%20Windows%20XP%20SP3%202016%20%2B%20Drivers%20v2.0%20By%20Computer%20Worms%20Team%2FGold%20Windows%20XP%20SP3%202016%20%2B%20Drivers%20v2.0.iso"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
